server:
  port: 8080

spring:
  profiles:
    include: local

  jpa:
    properties:
      ddl-auto: update
      hibernate:
        show-sql: true
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
